### ISSUE TITLE
Support account migration

### ISSUE THREAD

**Issue by kensanata** [kensanata/mastodon-backup#12]
In theory we could write a tool that reposts statuses to another instance. We would change all the public statuses to visibility *unlisted* in order to not pollute the local timeline of the destination instance. But it would still be super annoying for all the people mentioned in the statuses.
- Should we export just the last twenty?
- Should we limit ourselves to statuses not mentioning anybody?
- What about hashtags? We don't want to pollute hashtag searches, I think? Perhaps not a problem if we limit ourselves to twenty statuses?

**Comment by kensanata** [comment]
After thinking about this for a while, I think reposing a bunch of toots should be a manual process. It involves curation and a tool should not be doing it for you.

**Comment by Moelf** [comment]
for people who're migrating to a different instance (esp. to self-hosting), it would be useful to show how to import ActivityPub JSON as the admin of the new instance

**Comment by kensanata** [comment]
If you know how, please post it. I have no idea. You’d have to insert the rows directly into the database somehow. If you use the API the messages are also resent to all your followers and that’s not good.

**Comment by lapineige** [comment]
One could take a look at Calckey implement, which import everything without reposting the content (timestamps are preserved for instance).

**Comment by Moelf** [comment]
yeah I think fundamentally Mastodon implementation doesn't have it, so it can't be done gracefully

**Comment by lapineige** [comment]
> well, I guess that would tell you how to upload the data into a Calkey instance; since I run a GoToSocial instance, that would be different; same for Mastodon

For sure. I simply wanted to point to some hints for anyone willing to try this :)
