### ISSUE TITLE
Pagination for HTML output

### ISSUE THREAD

**Issue by cangyuyao** [kensanata/mastodon-backup#21]
Currently most users don't have many toots on their account so one single page HTML is enough for viewing all the contents, but it may not work well with a large number of toots. I have around 5000 toots now and it's already quite a long page. I think pagination would help browsing a large archive, such as every 3000 toots per page.

**Comment by kensanata** [comment]
Two simple Previous and Next links at the top and at the bottom of the page would be enough?

**Comment by cangyuyao** [comment]
I think it’s enough. All output files in the same folder and linked with prev and next files

**Comment by kensanata** [comment]
Take a look at 4d8cb2c. Good enough?

**Comment by cangyuyao** [comment]
Works perfectly for me. Thanks for the tool!
