### ISSUE TITLE
More stuff to report

### ISSUE THREAD

**Issue by kensanata** [kensanata/mastodon-backup#23]
`@marionline@mastodon.art` says: "How about a media counter how many media file were uploaded? Or if possible a hashtag counter, what hashtags one uses the most?"

**Comment by kensanata** [comment]
Adding this to `report.py` should be easy.

**Comment by wion** [comment]
The hashtag lister is a good idea. For auditors/curators/cherrypickers, it would make it easier to remember what to search for. Presumably anything with a hashtag is _slightly_ more important than just any old toot. Though not always; sometimes we forget to hash. ;)

**Comment by kensanata** [comment]
Right now (d83da68) I'm simply printing the top ten hashtags used. I'm not sure this would actually help in your use case.

```
$ mastodon-archive report kensanata@dice.camp
Statuses:               209
Boosts:                  14
Media:                    5
Favourites:             223

#caster:                  5
#20questions:             5
#introduction:            2
#osr:                     2
#currentprojects:         2
#caller:                  1
#rpgmusic:                1
#razorcoast:              1
#rpghaiku:                1
#haiku:                   1
```

Perhaps a list of all the hashtags you used and their count would be more useful for you? This is what 832c85e prints:

```
$ mastodon-archive report kensanata@dice.camp
Statuses:               209
Boosts:                  14
Media:                    5
Favourites:             223

#caster(5) #20questions(5) #introduction(2) #osr(2)
#currentprojects(2) #caller(1) #rpgmusic(1) #razorcoast(1)
#rpghaiku(1) #haiku(1) #character(1) #amaroq(1) #tootdon(1) #howto(1)
#spells(1) #history(1) #rpg(1) #myfirstcharacter(1) #1strpgs(1)
#favouritepen(1) #pbta(1)
```

**Comment by wion** [comment]
Yes, that wrapping list of all hashtags would be good and fine.
