### ISSUE TITLE
Report media and tags on boosted toots

### ISSUE THREAD

**Issue by BartG95** [kensanata/mastodon-backup#24]
The current report functionality reports the number of media attachments and the tags used in *your* toots, not in the toots you boosted.

I don't know if this should change by default, or only as an option. I think this depends a lot on the user: for me, 3/4 of my timeline consists of boosted toots, so I want this as a default. On the other hand, their might be people who see it the other way around.

I also don't know if these stats should be merged with the stats of your own toots. Maybe it should report three things: media in your toots, media in boosted toots and a total number of media attachments. Same for tags: most used tags in your toots, most used tags in boosted toots and most used tags in the combination of those two.

**Comment by kensanata** [comment]
Hm, interesting. I felt that I wanted to know how many files I had uploaded and what my hashtags were because I don’t boost very often and don’t consider the boosts “mine”. Maybe a simple —more option would be a good solution? Specially since the hashtag block can get quite big. Or perhaps we could add an option saying that we actually only care about the hashtags we recently used (half a year?).

**Comment by BartG95** [comment]
> Maybe a simple —more option would be a good solution?

Agreed.

> Or perhaps we could add an option saying that we actually only care about the hashtags we recently used (half a year?).

That would be a nice extra. Something like `--report-recent-weeks N`?

**Comment by kensanata** [comment]
Yeah, or a more generic `--newer-than N`.

**Comment by kensanata** [comment]
Solved in 3e8afb6.

**Comment by BartG95** [comment]
Hmm, not enterily solved: there isn't yet an option to include boosts in the tags. Feel free to apply the diff below (already tested):
````diff
diff --git a/mastodon_archive/__init__.py b/mastodon_archive/__init__.py
index 476e1f5..781dec5 100644
--- a/mastodon_archive/__init__.py
+++ b/mastodon_archive/__init__.py
@@ -106,9 +106,6 @@ if and only if they are in your archive''')
     parser_content.add_argument("--top", dest='top',
                                 metavar='N', type=int, default=10,
                                 help='only print the top N tags')
-    parser_content.add_argument("--include-boosts", dest='include_boosts', action='store_const',
-                                const=True, default=False,
-                                help='include boosts')
     parser_content.add_argument("user",
                                 help='your account, e.g. kensanata@octogon.social')
     parser_content.set_defaults(command=report.report)
diff --git a/mastodon_archive/report.py b/mastodon_archive/report.py
index e29f51b..990f2c5 100644
--- a/mastodon_archive/report.py
+++ b/mastodon_archive/report.py
@@ -39,14 +39,12 @@ def media(statuses):
     return i
 
 
-def tags(statuses, include_boosts):
+def tags(statuses):
     """
     Count all the hashtags in statuses
     """
     count = {}
     for item in statuses:
-        if include_boosts and item["reblog"] is not None:
-            item = item["reblog"]
         for name in [tag["name"] for tag in item["tags"]]:
             if name in count:
                 count[name] += 1
@@ -54,7 +52,7 @@ def tags(statuses, include_boosts):
                 count[name] = 1
     return count
 
-def print_tags(statuses, max, include_boosts):
+def print_tags(statuses, max):
     """
     Print hashtags used in statuses
     """
@@ -62,7 +60,7 @@ def print_tags(statuses, max, include_boosts):
         print("All the hashtags:")
     else:
         print("Top " + str(max) + " hashtags:")
-    count = tags(statuses, include_boosts)
+    count = tags(statuses)
     most = sorted(count.keys(), key = lambda tag: -count[tag])
     print(textwrap.fill(" ".join(
         ["#"+tag+"("+str(count[tag])+")" for tag in most[0:max]])))
@@ -108,7 +106,7 @@ def report(args):
         print("Media:".ljust(20), str(media(statuses)).rjust(6))
 
         print()
-        print_tags(statuses, args.top, args.include_boosts)
+        print_tags(statuses, args.top)
 
     if "statuses" in data and "favourites" in data:
         print()
@@ -119,4 +117,4 @@ def report(args):
         print("Media:".ljust(20), str(media(favourites)).rjust(6))
 
         print()
-        print_tags(favourites, args.top, args.include_boosts)
+        print_tags(favourites, args.top)
````

**Comment by kensanata** [comment]
Do you want to do this via a pull request? That way, author and all will be correct without me having to fiddle with the command line too much.

**Comment by BartG95** [comment]
Done by https://github.com/kensanata/mastodon-backup/pull/26
