### ISSUE TITLE
permissions of secrets

### ISSUE THREAD

**Issue by kensanata** [kensanata/mastodon-backup#28]
Do you think permissions on the files containing the tokens should be tighter? We could make sure Files are only readable and writeable by the user. Or we could go further and encrypt the files? I’m not sure what we want to do, for now. If you have an opinion on this, please comment.

**Comment by BartG95** [comment]
Definitely not encryption: that's up to the filesystem. Also, it makes scripts more difficult to make.
Probably the best thing to do is to put files in a seperate folder, so a user can decide how to secure that folder. I don't think securing the tokens is a responsibility of the program.
(I am no security expert, tho)
