### ISSUE TITLE
Option to avoid expiring pinned toots

### ISSUE THREAD

**Issue by seanlynch** [kensanata/mastodon-backup#32]
I use pinned toots to add stuff I'd otherwise put in my profile but won't fit. I don't want to expire these. It would be nice to have an option to never expire them.

**Comment by kensanata** [comment]
Yeah, I wondered about that when my pinned toots expired. Perhaps this doesn’t need an option but should simply be how it works.

**Comment by seanlynch** [comment]
That would certainly be fine with me, since one can always allow a pinned toot to expire simply by unpinning it.

**Comment by kensanata** [comment]
Possibly fixed by f6ae192. What do you think?

**Comment by kensanata** [comment]
If it doesn't work, create a new issue. :)
