### ISSUE TITLE
Toots not deleted?

### ISSUE THREAD

**Issue by MaiaDereva** [kensanata/mastodon-backup#37]
Hello @kensanata , 
I tried the command "expire" tonight (with the options --older-than 15 and --confirmed). Everything seemed to work well, the script processed during around 6 hours without any error mentioned. But when I visited my account this morning... every toots are still there! Did I miss something?
Note: I did archive my toots before expiring them.

**Comment by kensanata** [comment]
How strange. You’re the first to report such a silent failure. Let’s see whether anybody else reports this.

**Comment by MaiaDereva** [comment]
My mistake @kensanata : I scrolled far enough to see that they indeed have been deleted, **but** the general counter at the top is still the same (old total).

By the way: boosts are not deboosted?

**Comment by kensanata** [comment]
I'm not sure where the counter comes from. I guess even if it isn't decremented I'd be OK with that? Either way, I don't think I can influence it. So perhaps it's cached and it will reset, or it will not. We'll just have to live with that. As for unboosting boosts, I think think this should work. But at the same time, I got a patch by @zlg (https://github.com/kensanata/mastodon-backup/commit/036df62e97277f21672033e27bc21740e0230119) on Oct 3 called "Correctly delete boosts" ... so obviously there was a bug and I hadn't noticed. As release 1.1 was prepared on Oct 4 I guess it depends on which version you are using.

**Comment by MaiaDereva** [comment]
Hi! Yes, we can live with it, but maybe you can explain in the Help file that the total will (probably) not change after using the "expire" command?

I've installed the script the 8th of october: I don't know which version I'm using.
No worry, I cleaned them manually.
