### ISSUE TITLE
Can't install on Korean Windows

### ISSUE THREAD

**Issue by sftblw** [kensanata/mastodon-backup#43]
![image](https://user-images.githubusercontent.com/5573010/55529349-f208cb80-56db-11e9-8f4a-8174686a1157.png)

on running command : `pip3 install mastodon-archive`,

- Windows 10, Korean
- Korean defaults to CP949 on Windows `cmd.exe`
- I changed code page to 65001 (unicode) before installing by typing `chcp 65001`
- admin privileged `cmd.exe` shows same error message

I guess It will happen on CJK Windows too, but not tested in **C**hinese, **J**apanese windows

**Comment by kensanata** [comment]
Thanks for the screenshot. I’ll take a look.

**Comment by BartG95** [comment]
A few suggestions:
* try running it from powershell instead of cmd;
* try code page 850 instead of 65001.

**Comment by sftblw** [comment]
@BartG95 Thank you but nothing worked.

![image](https://user-images.githubusercontent.com/5573010/55594380-58dcc200-577a-11e9-8e3a-2fd6e78f70d8.png)
![image](https://user-images.githubusercontent.com/5573010/55594397-68f4a180-577a-11e9-97fe-6e195a35e65b.png)
![image](https://user-images.githubusercontent.com/5573010/55594408-6f831900-577a-11e9-87e3-c24779d67023.png)
![image](https://user-images.githubusercontent.com/5573010/55594418-79a51780-577a-11e9-9db2-3e19f40d9ab7.png)

**Comment by kensanata** [comment]
The code looks correct... Perhaps you can try it interactively by simply starting python3 and typing it? Like this, for example:

```
~/src/mastodon-archive$ python3
Python 3.7.3rc1 (default, Mar 13 2019, 11:01:15) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> with open("README.md", "r", encoding="utf-8") as fh:
...     long_description = fh.read()
... 
>>> print(len(long_description))
25939
```

This would allow us to understand whether this is a problem in Python, or a problem in the code used to install the project.

**Comment by sftblw** [comment]
via git clone ->

```
Microsoft Windows [Version 10.0.17763.437]
(c) 2018 Microsoft Corporation. All rights reserved.
(deleted lines)
L:\Documents\_codebase\GitHub>cd mastodon-backup
L:\Documents\_codebase\GitHub\mastodon-backup>python
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> with open("README.md", "r", encoding="utf-8") as fh:
...     long_description = fh.read()
...
>>> print(len(long_description))
25939
>>>
```

manually downloading from "files.pythonhosted.org" (where pip says) ->

(`Using cached https://files.pythonhosted.org/packages/b9/ac/ac703bd0a8aac433c00fea2f3c360542b6cc897ad741cedf30df43d04b4c/mastodon_archive-1.1.0.tar.gz` )

```
Active code page: 65001

E:\Desktop\mastodon_archive-1.1.0>python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> with open("README.md", "r", encoding="utf-8") as fh:
...     long_description = fh.read()
...
>>> print(len(long_description))
23911
>>>
```

files.pythonhosted.org code does not have encoding param.

```
from setuptools import setup

with open("README.md", "r") as fh:
    long_description = fh.read()

(intentionally removed below lines)
```

so This looks like already fixed by #38 but not released yet. (1.1.0 is before #38 be merged).

**Comment by BartG95** [comment]
Ah, of course. I assumed the current version included that patch already. Indeed, this is seems to be the solution. Thanks for reporting the bug and its solution 👍.
@kensanata can you make a 1.2.0 release?

**Comment by kensanata** [comment]
Done!
