### ISSUE TITLE
Split command doesn't exist ?

### ISSUE THREAD

**Issue by lapineige** [kensanata/mastodon-backup#51]
`mastodon-archive split --older-than=100 account@domain.tld`

> mastodon-archive: error: invalid choice: 'split' (choose from 'archive', 'media', 'text', 'context', 'html', 'expire', 'report', 'followers', 'following', 'mutuals', 'whitelist', 'login')

What's going on ?

Version 1.2.0

**Comment by kensanata** [comment]
This command was introduced a few days after the release of 1.2.0.

**Comment by lapineige** [comment]
Oh, too bad for me ^^
Then I need to install a master branch version ?

**Comment by kensanata** [comment]
Yes, or wait for a bit and over the weekend I can make a new release as there haven’t been any changes in a while.

**Comment by lapineige** [comment]
That's great :smiley:

**Comment by kensanata** [comment]
Fixed with 55187dc
