### ISSUE TITLE
--pace not working (since 1.3.0 ?)

### ISSUE THREAD

**Issue by lapineige** [kensanata/mastodon-backup#53]
The `--pace` option is no longer working for me, I'm not sure but maybe it's the case since my upgrade to 1.3.0.
And I'm using the same command for months, so it's not related to my way to write it (`--pace` at the end of the command, but I tried other locations)

**Comment by kensanata** [comment]
You didn't say for which command you used it? I've switched the way expiration works, see a8d5c8f.

**Comment by lapineige** [comment]
It was for mentions.
It's working for statuses.
Thanks.
