### ISSUE TITLE
[Proposal] Prevent specific statuses from being expired

### ISSUE THREAD

**Issue by lapineige** [kensanata/mastodon-backup#54]
As an user, I would like to expire all statuses older than X, but not a few of them.
In my particular case, I want not to expire some pinned toots, yet expire every statuses around them.

I see several way to do that, more or less specific to this exact scope:
- right now I could split the archive into 3 pieces around 1 status (1 before / 1 with the status/ 1 after), but it's really inconvenient
- mark certain toots (thanks to their URL/id ?) as "on hold", that can't be deleted
- add an option to keep pinned toots. That would be very convenient but very specific, and I don't know if it's doable
- allow to expire toots excepts the ones marked as favorite. Not very specific, but not completely compatible with the removal of favorites. 

What could be either for you, and how can we help you to implement that if you're willing to ?

**Comment by kensanata** [comment]
I think the code already [skips pinned toots](https://github.com/kensanata/mastodon-backup/blob/master/mastodon_archive/expire.py#L85-L89).

Incidentally, that would also be the place where you could add a test skip favourite toots. Can you mark your own toots as favourites? You could test the [favourited](https://docs.joinmastodon.org/entities/status/#favourited) property (`status["favourited"]`).

As for marking the toots as unexpirable by keeping a list of URLs in a text file… Yeah, you could do that, but it seems like a very brittle solution to me.

Feel free to start working on this ask questions. I'm happy to help but I don't think I will be implementing this myself.

**Comment by lapineige** [comment]
Well then it already skip them, that's perfect and all I want. Thanks !
