### ISSUE TITLE
Archive bookmarks

### ISSUE THREAD

**Issue by frainz-de** [kensanata/mastodon-backup#60]
It seems like bookmarks are not archived. Toots that are also favourited have the bookmark property set in the json archive but those that are only bookmarked are not present.
Also, it probably makes sense to add a bookmarks collection for the html and text generation.

**Comment by kensanata** [comment]
That's true! Do you want to work on it? I don't see myself working on this project all that much these days, unfortunately. I'd be happy to help if you have questions, though!

**Comment by frainz-de** [comment]
It doesn't seem very difficult to add this. I'll have to see when I have time to get into the code base

**Comment by loikein** [comment]
Hi, very happy to see this get implemented. @kensanata would you please add it to release? The PyPI version seems still unable to archive bookmarks. Thanks a lot!

**Comment by kensanata** [comment]
Done! Thank you all.
