### ISSUE TITLE
why GPL instead of AGPL?

### ISSUE THREAD

**Issue by cauerego** [kensanata/mastodon-backup#75]
i don't want to get into license debates here.

mastodon uses AGPL for very good reasons.

GPL is weaker.

why taking the step back if this is "merely" a mastodon tool?

**Comment by kensanata** [comment]
If you don’t want to open a license debate why are you doing just that? I don’t remember thinking much about it and simply copying a license file from one folder to another.

**Comment by cauerego** [comment]
cool, tiu just answered my question. thanks. 😘

**Comment by kcubeterm** [comment]
> simply copying a license file from one folder to another.

Great, and that is what I do also
